language: node_js
sudo: false
node_js:
  - '4'
  - '6'
  - '7'
  - '8'
  - '9'
  - '10'
script:
  - npm run ci
env:
  global:
    secure: "lzHHp+XjeJe1d7JuQW/N7Bu8bFvxQo3hBJgET2cgU9YYSRDUxLX7KblJRNPEMb6pn5sVdwfK9RTWVyhyZM39SQ02BJRtjzl4mB1+yd65Ln4Z4P2e23fApG/ZymyVMfU0Fq4LexBpTJ/fnXGZvv8pc6hTdwU5KnBSoJ/gQOw0F26D95ZoJ9EjuULsuA67sJtrA99g2RCgB8Er6/CXHYKI9hiCzxUIgvPVq/1g3Ityay5e46k7OySw8v+onIGbjcl1d7b86RkNi7DkCFIoC83Y8YMxgesWb1HOZUIOoL06Hno2zlJJf0eaMNa8fgfOZgzhR0Ufl34BfX3w2vHx4ksv0wbWr/YWHCAI3VFD2lmoyhWQhIyAfRN2QIEFsaCe7a0CinVtEZH7yUdiVucRRzUHZvwlKIaiHSyOca+90OSDqzQIcryDL2+b2WxMXjtpb5rY85L9E8UYaBaTKSbQY+J9NBdkfGWUxPDxs4modN4zvdVPMMzpD3tJEC02sc6E8QsuwpFbQD/U1OlXP2hg7htoLKE9mQwKwmLNdSFFTvqsudRdd7yIbTAgl41Xe67dnPfwPc0qvf1LH2jqfbBv7KgyjstzAicMydwoSUjRnnTLQi2sNuJ1xsEPx+qi8dR6nZCC0964MYbuIp4XEzc8W1zhbJ9D8+CBwbeRXUI88FzxRBg="
